replicaCount: 1

image:
  repository: nobeldhakal123/go-web-app
  tag: "23399371608"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: app.nobeldhakaltech.online
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

resources: {}
